QUANTITY = "Quantity"
SCRIP_NAME = "SCRIP NAME"
TYPE = "TYPE"
PRICE = "Price"

# Other constants
SCRIP = "Scrip"
BUY_PRICE = "BuyPrice"
SELL_PRICE = "SellPrice"
QUANTITY_PERCENTAGE = "Quantity_Percentage"
HOLDING = "Holding"
INVESTMENT_VALUE = "InvestmentValue"
INVESTMENT_VALUE_PERCENTAGE = "InvestmentValue_Percentage"
CURRENT_VALUE = "CurrentValue"
CURRENT_VALUE_PERCENTAGE = "CurrentValue_Percentage"
NET_PRESENT_VALUE = "NPV"
NET_PRESENT_VALUE_PERCENTAGE = "NPV_PCT"

scrip_map = {
    "AMRUTANJAN HEAL": "AMRUTANJAN",
    "RELIANCE INDUST": "RELIANCE",
    "ITC LIMITED": "ITC",
    "CIPLA LIMITED": "CIPLA",
    "STATE BANK OF I": "SBIN",
    "THE RAMCO CEMEN": "RAMCOCEM",
    "HDFC BANK LIMIT": "HDFCBANK",
    "BIOCON LIMITED": "BIOCON",
    "CADILA HEALTHCA": "ZYDUSLIFE",
    "TATA CONSULTANC": "TCS",
    "INFOSYS LIMITED": "INFY",
    "TECH MAHINDRA L": "TECHM",
    "TATA STEEL LIMI": "TATASTEEL",
    "GOVERNMENT OF I": "SGB",
    "NIPPON LIFE IND": "LIQUIDBEES",
    "ZOMATO LIMITED#": "ZOMATO",
    "SUNDARAM FINANC": "SUNDARMFIN",
    "RAMCO INDUSTRIE": "RAMCOIND",
    "BANK OF MAHARAS": "MAHABANK",
    "EXIDE INDUSTRIE": "EXIDEIND",
    "HDFC ASSET MANA": "HDFCAMC",
    "HDFC LIFE INSUR": "HDFCLIFE",
    "INDIAN ENERGY E": "IEX",
    "STT": "STT",
    "PTC INDIA FIN S": "PFS",
    "MOTILAL OS NASD": "MON100",
    "STAMP DUTY": "STAMP_DUTY",
    "SERVICE TAX": "SERVICE_TAX",
    "TOC BSE EXCHANG": "TOC_BSE",
    "TOC NSE EXCHANG": "TOC NSE",
    "WIPRO": "WIPRO",
    "HDFCBANK": "HDFCBANK",
    "HEIDELBERGCEMEN": "HEIDELBERG",
    "HDFCAMC": "HDFCAMC"
}
